---
- name: Collect WebSphere cluster/JVM/application info
  hosts: websphere_servers
  gather_facts: no
  vars:
    was_home: /opt/IBM/WebSphere/AppServer
    profile_name: AppSrv01
    wsadmin_user: wsadmin
    wsadmin_pass: wsadminpwd
    wsadmin_lang: jython

  tasks:
    - name: Run wsadmin to list clusters
      command: >
        {{ was_home }}/profiles/{{ profile_name }}/bin/wsadmin.sh
        -lang {{ wsadmin_lang }}
        -user {{ wsadmin_user }}
        -password {{ wsadmin_pass }}
        -c "print AdminTask.listClusters()"
      register: cluster_out

    - name: Run wsadmin to list servers (JVMs)
      command: >
        {{ was_home }}/profiles/{{ profile_name }}/bin/wsadmin.sh
        -lang {{ wsadmin_lang }}
        -user {{ wsadmin_user }}
        -password {{ wsadmin_pass }}
        -c "print AdminTask.listServers()"
      register: jvm_out

    - name: Run wsadmin to list applications
      command: >
        {{ was_home }}/profiles/{{ profile_name }}/bin/wsadmin.sh
        -lang {{ wsadmin_lang }}
        -user {{ wsadmin_user }}
        -password {{ wsadmin_pass }}
        -c "print AdminApp.list()"
      register: app_out

    - name: Print counts
      debug:
        msg: |
          Clusters: {{ cluster_out.stdout_lines | length }}
          JVMs: {{ jvm_out.stdout_lines | length }}
          Applications: {{ app_out.stdout_lines | length }}

    - name: Print raw details (optional)
      debug:
        var: cluster_out.stdout_lines
    - debug:
        var: jvm_out.stdout_lines
    - debug:
        var: app_out.stdout_lines
