---
- name: Collect WebSphere cluster/app info
  hosts: websphere_cells
  gather_facts: no

  tasks:
    - name: Copy Jython script to Dmgr01
      copy:
        src: cluster_app_report.py
        dest: /tmp/cluster_app_report.py
        mode: '0644'

    - name: Find wsadmin.sh owner
      stat:
        path: /usr/WebSphere*/AppServer/profiles/Dmgr01/bin/wsadmin.sh
      register: wsadmin_stat

    - name: Run wsadmin as file owner
      shell: >
        {{ wsadmin_stat.stat.path }}
        -lang jython -f /tmp/cluster_app_report.py
      register: cluster_report
      become: true
      become_user: "{{ wsadmin_stat.stat.pw_name }}"

    - name: Collect cluster report facts
      set_fact:
        all_reports: "{{ (all_reports | default([])) + cluster_report.stdout_lines }}"

  # Run once on localhost to consolidate results
  - name: Write consolidated CSV
    hosts: localhost
    gather_facts: no
    tasks:
      - name: Ensure reports directory exists
        file:
          path: ./reports
          state: directory

      - name: Write single combined CSV file
        copy:
          dest: ./reports/websphere_cluster_report.csv
          content: |
            hostname,cluster_name,node_count,jvm_count,app_count
            {% for line in hostvars | dict2items %}
            {% if line.value.all_reports is defined %}
            {% for row in line.value.all_reports %}
            {{ row }}
            {% endfor %}
            {% endif %}
            {% endfor %}
